config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  resources :messages
  get 'chatroom/show'
  # require 'sidekiq/web'
  # require 'sidekiq-scheduler/web'

  # devise_for :users
  # get 'books/search'
  # get 'bookmarks/create'
  # get 'bookmarks/destroy'

  # Defines the root path route ("/")
  # root "articles#index"
  # get 'mypage', to: 'users#me'
  root to: 'books#index'
  # root "home#top"
  # devise_for :users, controllers: {
  #   # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
  # registrations: "users/registrations",
  #   sessions: "users/sessions",
  # passwords: "users/passwords",
  #   confirmations: "users/confirmations"
  # }
  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
  #   [user, password] == ['admin', Rails.application.credentials.basic[:user_password].to_s]
  # end

  # authenticate :user do #authenticate
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # resources :users, only: %i[show edit update]

  resources :books, param: :isbn do
    collection do
      get :search
      get :autocomplete
    end
    resources :bookmarks, only: %i[create destroy], shallow: true
    resources :favorites, only: %i[create destroy]
  end
  resources :bookmarks, only: %i[index edit update]
  get 'bookmarks/my_bookmarks', to: 'bookmarks#my_bookmarks'
  resources :favorites, only: %i[index destroy]
  get '/api/test', to: 'application#test'
end

app/views/shared/_before_login_header.html.erb
<header class="flex justify-center items-center h-20 p-6 border-y-2">
  <div class="w-full max-w-7xl flex justify-content">
    <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl p-5 mx-auto md:items-center md:justify-center md:flex-row md:px-6 lg:px-8">
      <div class="flex flex-row items-center justify-center lg:justify-start">
        <a href="/" class="text-lg font-bold tracking-tighter text-blue-600 transition duration-500 ease-in-out transform tracking-relaxed lg:pr-8" data-action="sidebar#toggle">
          <%= image_tag asset_path("facebook_cover_photo_1.png"), class: "h-12", viewBox: "0 0 28 24", fill: "none" %>
        </a>
      </div>          
      <nav :class="{'flex': open, 'hidden': !open}" class="flex-col items-center flex-grow hidden pb-4 border-blue-600 md:pb-0 md:flex md:justify-end md:flex-row lg:border-l-2 lg:pl-2">
      </nav>
    </div>
  </div>
  <nav>
    <button id="button" type="button" class="fixed z-30 top-6 left-6">
      <i id="sidebar" class="fa-solid fa-sidebar fa-2x"></i> 
      <i id="bars" class="fa-solid fa-bars fa-2x"></i>
      <i id="xmark" class="fa-solid fa-xmark fa-2x invisible"></i>
    </button>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer aria-label="Site Footer" class="bg-green-100">
  <div
    class="max-w-screen-xl px-2 mx-auto lg:px-2 p-2"
  >
    <div
      class="grid grid-cols-1 gap-8 pt-8 border-t border-gray-100 sm:grid-cols-2 lg:grid-cols-4 lg:pt-4"
    >
      <p class="footer-title"><%= link_to 'BOOKSTAIRとは', page_path('about') %></p> 

      <p class="footer-title"><%= link_to '利用規約', page_path('tos') %></p> 

      <p class="footer-title"><%= link_to 'プライバシーポリシー', page_path('privacy') %></p> 

      <p class="footer-title"><%= link_to 'お問い合わせ', "https://docs.google.com/forms/d/e/1FAIpQLSc8c7jZnpeaIUn6YU58M1_ESvGrP-1hpnJ3U5cReXZIu7YjMQ/viewform?embedded=true", class: 'nav-link' %></p> 
    </div>
    <div>
      <p class="text-xs text-gray-500">
        Copyright &copy; 2022-2023. BOOKSTAIR
      </p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header aria-label="Page Header" class="bg-green-100">
  <div class="max-w-screen-xl px-2 py-2 mx-auto sm:py-2 sm:px-2 lg:px-2">
    <div class="sm:flex sm:items-center sm:justify-between">
      <div class="text-center sm:text-left">
        <div class="flex-1 md:flex md:items-center md:gap-12">
          <a class="block text-teal-600" href="/">
            <%= image_tag asset_path("facebook_cover_photo_1.webp"), class: "h-12", viewBox: "0 0 28 24", fill: "none" %></a>
          </a>
        </div>
      </div>
      <div class="flex justify-end gap-4 mt-4 sm:mt-0 sm:items-center text-xs">
        <div class="flex flex-col items-center">
          <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z"></path>
          </svg>
          <% if user_signed_in? %>
            <span><%= current_user.name %></span>
          <% else %>
            <span class="text-xs">こんにちは</span>
          <% end %>
        </div>
        <div class="flex flex-col items-center">
          <%= link_to root_path, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
              <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
            </svg>
            <span class="text-xs">共有本棚</span>
          <% end %>
        </div>

        <div class="flex flex-col items-center">
          <%= link_to search_books_path, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607zM10.5 7.5v6m3-3h-6"></path>
            </svg>
            <span class="text-xs">本を登録</span>
          <% end %>
        </div>
        
        <% if user_signed_in? %> 
          <div class="flex flex-col items-center">
            <%= link_to bookmarks_path, class: "flex flex-col items-center text-xs" do %>
              <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"></path>
              </svg>
              <span class="text-xs">投稿一覧</span>
            <% end %>
          </div>
        <% end %>

        <% if user_signed_in? %> 
          <div class="flex flex-col items-center">
            <%= link_to favorites_path, class: "flex flex-col items-center text-xs" do %>
              <svg class="h-8 w-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path>
              </svg>
              <span class="text-xs">お気に入りの本</span>
            <% end %>
          </div>
        <% end %>

      <%= link_to bookmarks_my_bookmarks_path do %>
        <div class="flex flex-col items-center">
          <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"></path>
          </svg>
          <%# if user_signed_in? %>
            <span class="text-xs">自分の投稿一覧</span>
          <%# end %>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <div class="flex flex-col items-center">
          <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M22 10.5h-6m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z"></path>
            </svg>
            <span class="text-xs">ログアウト</span>
          <% end %>
        </div>
      <% else %>
        <div class="flex flex-col items-center">
          <%= link_to new_user_registration_path, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m8.25 3v6.75m0 0l-3-3m3 3l3-3M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z"></path>
            </svg>
            <span class="text-xs">新規登録</span>
          <% end %>
        </div>
        <div class="flex flex-col items-center">
          <%= link_to new_user_session_path, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z"></path>
            </svg>
            <span class="text-xs">ログイン</span>
          <% end %>
        </div>
        <div class="flex flex-col items-center">
          <%= link_to users_guest_sign_in_path, data: { turbo_method: :post }, class: "flex flex-col items-center text-xs" do %>
            <svg class="w-8 h-8" data-darkreader-inline-stroke="" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z"></path>
            </svg>
            <span class="text-xs">ゲストログイン</span>
          <% end %>
        </div>
      <% end %>
        <!-- </ul> -->
      </div>
    </div>
  </div>
</header>

app/views/shared/_intro_button.html.erb
<button id="start-tour" class="button is-info is-rounded is-focused mt-1 font-semibold">投稿のチュートリアル</button>

<script>
  intro = introJs();
  // intro = introJs(".introduction-farm").start();
  
  document.querySelector('#start-tour').onclick = function() {
    intro.start();
  };
</script>

app/views/shared/_search.html.erb
<form class="p-1 flex justify-center items-center" action="/books/search" method="get" data-controller="autocomplete"><!-- data-controller属性の値とJavaScriptのファイル名が紐づく(この場合だとautocomplete.js)-->
  <%= form_with url: nil, method: :get, data: { controller: "autocomplete" } do |f| %><!-- data: { controller: "autocomplete" }　でコントローラでこのテキストボックスを参照できるようになります-->
    <div class="flex items-center justify-center w-5/6">
      <label for="Bookname" class="w-full px-3 py-2 rounded focus-within:border-blue-600">
        <%= f.search_field :title_search, value: params[:title_search], placeholder: "検索: 書籍名", class: "w-full p-4 mx-auto text-sm border-sky-400 rounded-lg bg-slate-50 border-2", type: "text", data: { target: "autocomplete.input" } %>
      </label>
      <%= f.submit "検索", class: "submit-button inline-block rounded border border-sky-600 bg-sky-600 px-4 py-2 text-sm font-medium text-white focus:ring active:text-sky-500" do %>
        <i class="fas fa-search"></i>
      <% end %>
    </div>
    <ul data-autocomplete-target="results"></ul>
  <% end %>
</form>